### ISSUE TITLE
redundant template parameter

### ISSUE THREAD

**Issue by mywtfmp3** [mywtfmp3/BoostGraphTutorial#1]
Algorithm 40 has a redundant template parameter `vertex_descriptor`. It can be replaced by `typename boost::graph_traits<graph>::vertex_descriptor`.

```cpp
#include <boost/graph/adjacency_list.hpp>

template <
  typename graph,
  typename vertex_descriptor
>
typename boost::graph_traits<graph>::edge_descriptor
get_edge_between_vertices(
  const vertex_descriptor& vd_from,
  const vertex_descriptor& vd_to,
  const graph& g
)
{
  const auto er = edge(vd_from, vd_to, g);
  if (!er.second)
  {
    std::stringstream msg;
    msg << __func__ << ": "
      << "no edge between these vertices"
    ;
    throw std::invalid_argument(msg.str());
  }
  return er.first;
}
```

**Comment by richelbilderbeek** [comment]
I agree (as often is the case on your review). I assume used the -I agree- redundant template type for a reason, but time may have been a factor as well.

Let's hope Travis CI does its thing again fast (I check on a daily basis), to get your suggestions in.

Keep up the great work!
